name: Data Generation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  datagen:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :spatial:assemble
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./gradlew :spatial-neoforge:assemble
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Compiled
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: spatial/build

      - name: Store Compiled
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-neo
          path: spatial-neoforge/build