# REQUIRES DATAGEN TO BE CALLED IN A JOB BEFORE THIS!!

name: Publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    name: Publish Code as Github Package - ${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Pull Compilation Data
        uses: actions/download-artifact@v4
        with:
          name: build
          path: spatial/build

      - name: Pull Compilation Data (Main)
        uses: actions/download-artifact@v4
        with:
          name: build-neo
          path: spatial-neoforge/build

      - name: Publish
        run: ./gradlew :spatial:publish
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}