name: Publish and Announce Nightly Build

env:
  GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/**/*"
      - "**/*.gradle.kts"
      - "**/gradle.properties"

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-22.04
    outputs:
      version: ${{steps.version.outputs.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 150
          fetch-tags: true

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "spatial"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true

  build:
    needs: [ vars ]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}

#  tests:
#    needs: [ build, vars ]
#    uses: ./.github/workflows/_run-gametests.yml
#    secrets: inherit
#    with:
#      version: ${{ needs.vars.outputs.version }}

  publish:
    needs: [ vars, build ]
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    with:
      version: ${{ needs.vars.outputs.version }}